### ISSUE TITLE
Importar Turmas

### ISSUE THREAD

**Issue by gscnogueira** [nosgueira/CAMAAR#1]
Como um usuário da API para o SIGAA,
Eu quero ter acesso ao site por meio de um login e uma senha e ter acesso a um json contendo as informações sobre cada turma disponível para 
um usuário do SIGAA, sendo elas: nome da turma, código da disciplina, código da turma, semestre e horário
Para que eu consiga ter acesso aos dados de cada uma dessas turmas.

**Comment by EduardoAfInacio** [comment]
Funcionalidade implementada. JSON está sendo retornado e a renderização de suas respectivas informações no frontend está correta.
